on: push

jobs:
  job-a:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Step 1
        run: echo "Hello from Job A"
      - name: Step 2
        run: sleep 3
      - name: Step 3
        run: echo "Goodbye from Job A"
    outputs:
      job-a-id: ${{ github.job }}
      workflow-id: ${{ github.run_id }}

  job-b:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install @octokit/rest
      - name: Cancel Job A
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await octokit.actions.cancelWorkflowRun({
              owner,
              repo,
              run_id: ${{ needs.job-a.outputs.workflow-id }},
            });
            console.log(data);

  # run-test:
  #   runs-on: ubuntu-latest
  #   env:
  #     ACTIONS_RUNNER_DEBUG: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build the Docker express image
  #       run: |
  #         cd reporte
  #         docker build -t express:1 .
  #     - name: Run docker express
  #       run: docker run -p 5001:5001 -d --name express-docker express:1

  #     - name: Build the Docker react image
  #       run: |
  #         cd frontend
  #         docker build -t react:1 .
  #     - name: Run docker react
  #       run: docker run -p 3000:3000 -d --name react-docker react:1

  #     - name: Run cypress
  #       run: | 
  #         cd frontend
  #         yarn add cypress --dev
  #         npx cypress run --record --key 2df36ced-321d-442d-870b-8f588f982f85
          

  # cypress:
  #   needs: [express]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: "frontend"
  #         build: yarn build
  #         start: yarn start
