on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Start Server A
        run: npm start server-a.js
      - name: Deploy A
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build-a
      - name: Deploy B
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build-b
        needs: Deploy A

  # cypress-run:
  #   # needs: [express-run]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: "frontend"
  #         build: yarn build
  #         start: yarn start
