on: push

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services: 
      back:
        #### Docker compose
        - name: Run docker composes
          run: docker-compose up --build -d
        ports:
          - 8000/tcp
          - 5001/tcp

    steps:
      - uses: actions/checkout@v3
      - name: Docker ps
        run: docker ps

      - name: Run migrate on django
        run: docker-compose exec -T django python manage.py migrate

      - name: Run createsuperuser on django
        run: |
          docker-compose exec -T django python manage.py shell
          docker-compose exec -T django echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin1234')"

      # - name: yarn install for fronend
      #   run: |
      #     cd frontend
      #     yarn install

      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      #   with:
      #     record: true
      #     working-directory: frontend
      #     build: yarn build
      #     start: yarn start
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  
