on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker express image
        run: |
          cd reporte
          docker build -t express:1 .
      - name: Run docker express
        run: docker run -p 5001:5001 -d --name express-docker express:1

      - name: Build the Docker react image
        run: |
          cd frontend
          docker build -t react:1 .
      - name: Run docker react
        run: docker run -p 3000:3000 -d --name react-docker react:1

      - name: Run cypress
        run: | 
          cd frontend
          yarn add cypress --dev
          npx cypress run --record --key 2df36ced-321d-442d-870b-8f588f982f85
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      #   with:
      #     working-directory: "frontend"
      #     build: yarn build
      #     start: yarn start
      #   env:
      #     # overwrite commit message sent to Cypress Cloud
      #     COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
      #     # re-enable PR comment bot
      #     COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}

  # cypress:
  #   needs: [express]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: "frontend"
  #         build: yarn build
  #         start: yarn start
