on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #### Docker compose
      - name: Run docker composes
        run: docker-compose up --build -d

      - name: Docker ps
        run: docker ps

      - name: Run migrate on django
        run: docker-compose exec -T django python manage.py migrate

      - name: Run createsuperuser on django
        run: |
           docker-compose exec -T django python manage.py shell < code/create_user_test.py

      - name: yarn install for fronend
        run: |
          cd frontend
          yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          working-directory: frontend
          # build: yarn build
          start: yarn dev
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
