on: push
jobs:
  express-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "reporte"
          # install: yarn install
          build: yarn build
          start: yarn start
      # - run: yarn install
      # - run: yarn build
      # - run: yarn start

  cypress-run:
    needs: [express-run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: "frontend"
          build: yarn build
          start: yarn start
