on: push

jobs:

  express:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        cd reporte
        docker build -t express:1
    - name: Run docker 
      run: docker run -p 5001:5001 -d --name express-docker express:1 
    - name: check docker
      run: docker -ps
    - name: stop docker
      run: docker stop express-docker
    

  # cypress-run:
  #   needs: [express-run]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: "frontend"
  #         build: yarn build
  #         start: yarn start
