on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    # env:
    #   ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      #### DJANGO
      - name: Build the Docker django image
        run: |
          cd mysite
          docker build -t django:1 .
      - name: Run docker django:1
        run: docker run -p 8000:8000 -d --name django-docker django:1
      #### Express
      - name: Build the Docker express image
        run: |
          cd reporte
          docker build -t express:1 .
      - name: Run docker express:1
        run: docker run -p 5001:5001 -d --name express-docker express:1
      #### React && Cypress
      - name: yarn install
        run: |
          cd frontend
          yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          working-directory: frontend
          # build: yarn build
          start: yarn dev
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
