on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #### Docker compose
      - name: Run docker composes
        run: docker-compose up --build -d

      - name: Docker ps
        run: docker ps

      - name: Run migrate on django
        run: docker-compose exec -T django python manage.py migrate

      - name: Run createsuperuser on django
        run: |
           docker-compose exec -T django echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@cyd.cl', 'admin1234')" | python manage.py shell

      - name: yarn install for fronend
        run: |
          cd frontend
          yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          working-directory: frontend
          # build: yarn build
          start: yarn dev
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
