on: push
jobs:
  expres-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Download docker
        uses: docker pull nicolashc1/express
      - name: run Docker
        uses: docker run -p 5001:5001 -d --name docker-express express
      - name: Check docker run
        uses: docker ps
      - name: Close docker
        uses: docker stop docker-express
      # - name: Start server 2
      #   env:
      #     SERVER_1_URL: http://localhost:5001
      #   run: |
      #     cd frontend
      #     yarn install
      #     until $(curl --output /dev/null --silent --head --fail $SERVER_1_URL); do
      #       printf '.'
      #       sleep 5
      #     done
      #     yarn build
      #     yarn start
    

  # cypress-run:
  #   needs: [express-run]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         working-directory: "frontend"
  #         build: yarn build
  #         start: yarn start
